version: '3.9'

services:
  app:
    build: .
    container_name: ecommerce_app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start

  mongo:
    image: mongo:6
    container_name: ecommerce_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
